### ISSUE TITLE
type error on centos

### ISSUE THREAD

**Issue by noelmcloughlin** [journeymidnight/radoshttpd#2]
```
radoshttpd/rados/striper.go:61: cannot use sp.ioctx (type _Ctype_rados_ioctx_t) as type
_Ctype_rados_striper_t in argument to func literal\nmake: *** [s3] Error 2'}
```

I have `librados-devel` installed (obsoletes librados2-devel`  `ceph-devel` )

**Comment by hopkings2008** [comment]
@noelmcloughlin what is the version of librados-devel do you use? if you use the librados of ceph 14, you can pick up the lastest commits from master branch, it has fixed the problem you found. Pls check this commit "https://github.com/journeymidnight/radoshttpd/commit/6df3523aa9e32609428256898688054dd86393c3".

**Comment by noelmcloughlin** [comment]
CentOS package versions are always lagging behind everyone else.  Let me
see what I find and get back to you.

**Comment by noelmcloughlin** [comment]
I installed this package on CentOS7

librados-devel.x86_64 2:14.2.8-0.el7 from https://download.ceph.com/rpm-nautilus/el7/X86_64

**Comment by noelmcloughlin** [comment]
Okay, I think this can be closed. I don't have the latest master. thanks.
